// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-enable'
  | 'pref-help'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish';
